language: generic

deploy:
  provider: s3
  access_key_id:
    secure: SxhxsSaaIsd8HobZLMd9hNz2FzUDpM8tKS1Af9sWI4oc0yzANLtS9QFrk28wUrVnLfcKYldcm7jXx14HDSd6KCYVLO9omITBJWUZTA4XJRxGLyjfQAZ6oYjkCeEUL0xEaSgaI1jUGYKQeroYl/5/ZFu19sYwWgAYD0aZvi5Xcrf3Z4VSbKpDP2aN20unPLOJewOc5/NUOrHjGEjcH1Hbnmwsm0TbKrfF+OnEw+1VfeBFoKmRmQ62fs1rg20jp+ZAYI7R+yGx1D1/VJBVInFXelVGLqvUUMaB9gE8EUw6hCT8efISpEYCBLnP02Gd7QRrrGtvFAx9FyMJLQDqWD3pOVY3gS4KCgWIePpFVBc0+6xBeNLc3isue+1Vg5G/fpO+tw+cFWlZF76Zd8QSb9z7K7JpvnPKy5UPGgQ+NlNpoW7epT1rMi8c3LDIGCNMBUJLUEv2F5lAZ5Xp1wDz1/N+eYzFdwg/J4p669PMDwla7s0vDx31kkfjYgj6Fx3qKkt2kL0nmiQICsg8Sk/uFkyg5qGlFTFocDsM5wc8Tb5ehpvqKSwCLdVoCgB8nDDvN5NL0Tagl+DdK4YOFyni5c+4NDkvbv4cAQYzYixsuMVvqVopOoSKSx+FZDVIEx4iGb267WO9Hv2Ewn7VBBXy4X0JGbgqYFrmykwoI17vY6PttbI=
  secret_access_key:
    secure: qXY8rvEQ7TFxh7N7oUgeBFG+K0e/q+qInLPdy8s4+uqeITyDi9WCxJoT5K9tt89FAwkfyY71VValof3PPQ48jl4Ff7ybvnWBFMwKnauqa7dxWCVR4zBk90C2FO5dXqL/xbMsHZ5nRVK9941yl19WnmULjVaBgRO2VuJMsEU2H8nCOeF7f2+CQq0kGwwrv2FMLkJPkzMbVEZPxaNXsnpSq4j1T85UW9aorXM0aFRmZ+XWdvLWeLrq2mLd5NeDXNM0ScLs8i3NBhdtUflbkGwSvj3AjU3iBCEsKugdjZoA0Toxp9+l4AVHRmOtVCPOUwLNrRgf7wGoqrsvpwWNCXBl5vyAhOy3TRV4XhFx4rSi8h18Bt0E8A1y5RZRg6SpBSJ2NidEo6l6Hz5EqxTwE3y1tqDSmRQx37bcczED0URLqLe8k+HORiBQIcZ9pNqxAyURJsNCUyoLQRpZTj7hLxU8ffKbDeOKPogOEvCbOwfQCl1VE8ZDh7VoI0U3xnwS5ED5s4deA1JmzLKQF0ZfQsM4JiuM890EbJQjmAthIk3Rbklb44dBItacQPbOC8xm/OANVrxqNlNBwLCTG2pnjSMX0zVErOrVWGVVjZlfcGZiQ22cmk2XbHw6SzD3VXmWtaTxcXGLytRTJMGU9GaixZvg2Fb6TfEPi4meLvKCVX/QsMM=
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  local_dir: www
  default_text_charset: utf-8
  detect_encoding: true
