language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "JCB1S73iX2NzpdEXcZ/iOiaZNV4KSh3nseK7wIXU48UqM1JY4ZiUTgqxzMgP2MFlKx3536/OSmKJxwdmsLvjVMy5T8GRgEKRIcYp4tGk4I0UtsqUGIVOU/reWGQ1eU6ifvBifbJmnQeDPxL/bs0UnZVWO2rQPYPqIfvDm+v6itJ4GZK0kYnfOGw9NiY3rwXtULehteyVUWGazKTeAUlZ9UK+epL6hS0ukF1lD/8Hk6o4u2mX5KyfXmTuEetMY5VoR0XRPRqyXN8BB8y1XUwTsoX4eZdg8uKjOGw5PnUtTcbuMvfZGkIVD6S1x0CHMwk3XNsXVsN+uvHpkayVe0k1yyQnW1HIjvXZ601rQOHUn4XfhaWOEM13EBNh4auDIwYBFXnvB2ltZJFTwEGoXEDCTqseBhrCmkfXYYqqMZSKWgIxr+XyLPecSnamgb+fRACMjRLg8opg6M7ie+JMrfdn4xnoYYTMz/3EPymR3s7u8AapgLD5GiEtcVOxyksolI2cGB8UrTjA/uzaLyaiUI6Oj/ew7YsHtsjoVXW0DShVZBN+eu1o/3tJlpSKOiCwhnRPyCa6DV8vC1RcOUvAZSTVWzm0p/HLrHeX3azETreevlh03/X09p2qD5ZOePl/34+GpBOT4q2rb48V/w2y9z5hetiTH77GVVf779OZ9vU+HMI="
  secret_access_key:
    secure: "QtwxpXYFtObzhhSZm4OAEaJBzlwahR34RuEWjaxAG1wNQpsHLMz02fXDz42K1Ko+3TDaK2hxs2vwQM1BCYXhSE49JURDnu3VD+GwKkgiET1+GL5CT7oS9jyRW1+JfpCiw0a8lGyUL5ujNDdtIYpd/XaUeRdMaQI8af1iZJERYlfgDgY5Qir3UDzvg5M4aolZebqH38EbDX1Luln2NyNtAPLRyDAHCLwUNcMv4O9OeAaxS8JIHwdjU88RtWzR4RWaFbTsD4KDzwA9aGNWC+oMIrSpMWEoBmwQeHebyNZ7yLAigL3poudyWI/q0zeCj6Xih26JEe3E/t+pbF3FN8viR6uIsH3tUfmoQYoQ+nP3EILWQktnpRAH51pO7+ZgSbxbEX82Fzl6Qo7sBKS4EFQ8Q0ku5ApiWpfxC95rCTUmi22mrmpPv9jSj+n6yvb3eNKoAEaQX+Y3lrIV8AIbH7J9UqHttpHu4w1GyvW2g/JynAF19m7KOkM2a2GHX9CehbRggDY1RAElAzj0/vs84rfYieZjb/IpeR3gPf3+k2qvKDXAho9ewZDzt0Op4FeGAusBra/lcjrCiSS2kS4nkTBFglSmnvOvF96pPnW0YbOMglBwuVK/NQwSxUbAv/vfh44vBr2IwmrKpM6mOszLktV0Unsu/FCETxLhs9mPBWmlsuk="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
